# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5089f1f78f99c840eb7892324214ac376a1f0cef292b39655ec7c381d08904237e664eaefb5386c226684cfdbee90f45f9ab648e4b6486d263e4220d267df39f

test:
  secret_key_base: fcdf31a314c3b465e3fcf8f561c13c93b6733879e56ddd64f54a23eb7b4a9436f39dfba0eeb676ebfa1924c1082f113231a035256c95734e0d96486bf33cea08

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
